---
apiVersion: core.oam.dev/v1alpha2
kind: TraitDefinition
metadata:
  name: manualscalertraits.core.oam.dev
spec:
  definitionRef:
    name: manualscalertraits.core.oam.dev
---
apiVersion: core.oam.dev/v1alpha2
kind: WorkloadDefinition
metadata:
  name: containerizedworkloads.core.oam.dev
spec:
  definitionRef:
    name: containerizedworkloads.core.oam.dev
---
apiVersion: core.oam.dev/v1alpha2
kind: Component
metadata:
  name: example-component
spec:
  workload:
    apiVersion: core.oam.dev/v1alpha2
    kind: ContainerizedWorkload
    spec:
      containers:
      - name: wordpress
        image: wordpress:4.6.1-apache
        env:
        - name: TEST_ENV
          fromSecret:
            name: replaceme
            key: replaceme
        ports:
        - containerPort: 80
          name: wordpress
  parameters:
  - name: instance-name
    required: true
    fieldPaths:
    - metadata.name
  - name: image
    fieldPaths:
    - spec.containers[0].image
  - name: env-var
    fieldPaths:
    - spec.containers[0].env[0].fromSecret.name
  - name: env-var-key
    fieldPaths:
    - spec.containers[0].env[0].fromSecret.key
---
apiVersion: core.oam.dev/v1alpha2
kind: ApplicationConfiguration
metadata:
  name: example-appconfig
spec:
  components:
  - componentName: example-component
    parameterValues:
    - name: instance-name
      value: example-appconfig-workload
    - name: image
      value: wordpress:php7.2
    - name: env-var
      value: test
    - name: env-var-key
      value: key
    traits:
    - trait:
        apiVersion: core.oam.dev/v1alpha2
        kind: ManualScalerTrait
        metadata:
          # TODO(negz): This name can be omitted and generated automatically if
          # each trait kind may apply only once to a component/workload.
          name:  example-appconfig-trait
        spec:
          replicaCount: 3