apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: k8scluster
spec:
  classSelector:
    matchLabels:
      oam: test
  writeConnectionSecretToRef:
    name: k8scluster